//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string TenTK { get; set; }
        public string MatKhau { get; set; }
        public long MaDG { get; set; }
    
        public virtual DocGia DocGia { get; set; }
    }
}
