//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTV
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhieuPhat
    {
        public long MaPhieuPhat { get; set; }
        public long MaPhieuMuon { get; set; }
        public string MaPhat { get; set; }
        public string Masach { get; set; }
    
        public virtual Phat Phat { get; set; }
        public virtual PhieuMuon PhieuMuon { get; set; }
        public virtual ChiTietPhieuMuon ChiTietPhieuMuon { get; set; }
    }
}
